### ISSUE TITLE
How to use a UserControl for QuickAccessItems

### ISSUE THREAD

**Issue by juergschweigi** [fluentribbon/Fluent.Ribbon#383]
Hallo Bastian,
i want to manage the QuickAccessItems in a separate UserControl with a ControlTemplate or so.
Is there a Possibility to do this???

I'd try this:
<Fluent:Ribbon.QuickAccessItems>
   <Fluent:QuickAccessMenuItem  Template="{StaticResource QAT}"/>
</Fluent:Ribbon.QuickAccessItems>

but it doesn't work correctly. The Menu from the Template is shown, but the checked Items don't appear in the QuickAccessToolbar!!! see the attached Image
![image](https://cloud.githubusercontent.com/assets/22076843/21286594/fb1f96f8-c458-11e6-83ed-28ac4c6551c5.png)

Gruß Jürgen

**Comment by batzen** [comment]
That's a bug that should have been fixed a few weeks ago.
As you didn't provide a version i can't say more.

Could you try to reproduce this by using the latest source version from the develop branch?

**Comment by juergschweigi** [comment]
Hallo Bastian,
actually i'd used the Version 4.0.3.394.
But now i've just downloaded your last Project (Version 5.0.0.0) from github.com!

I tried putting your QuickAccessItems from your TestUserControl (TestContent.xaml) into a separate UserControl "QAT.xaml" and added a new ControlTemplate in the "Grid.Ressources":
<Grid.Resources>
...
   <ControlTemplate x:Key="QAT">
      <local:QAT/>
   </ControlTemplate>
...
</Grid.Resources>
But I didn't find a possibility, to add this ControlTemplate into the Section of the QuickAccessMenuItems!!!
In Addition, the References from the QuickAccessMenuItems to the Targets don't work in the UserControl "QAT.xaml". What's wrong???

Secondly: 
Normally I manage my packages with VS2015 with NugetManager. I don't find the new Fluent.Ribbon.Package (5.0.0.0) on Nuget.org! 
How can I get Information for Access to a new Version of Fluent.Ribbon without allways visiting your page on github???

Thanks
Jürgen

**Comment by batzen** [comment]
5.0 is still a preview, you need to check "Include prerelease", but be careful with that one as the packages being release as prerelease tend to be unstable/include major bugs.

If this still happens with 5.0 i would need a working repro for your issue.

**Comment by juergschweigi** [comment]
Hallo Bastian,
in Version 5 it is also impossible to use an UserControl for the QuickAccessMenuItems.
And there are more Problems:
I've binded the Visibility of the MenuItems to UserSettingsProperties in a ViewModel. In Menu it works correctly, but in QuickAccessToolBar the collapsed Items are still shown, see below:
![image](https://cloud.githubusercontent.com/assets/22076843/21343312/65422e58-c696-11e6-8a70-c6b5ae4a17af.png)

Grüße Jürgen

**Comment by batzen** [comment]
As already said, i'd need a repro to really see what's going on.

**Comment by juergschweigi** [comment]
I don't know, what you mean with Repro???
in an earlier issue I read, that your interest in QAT is going to Zero :-) But our users want to manage several Functions in a QAT, so we have to implement this.

For seeing the issues push your QuickAccessMenuItems into a separate UserControl like "MyQAT.xaml" with Binding the VisibilityProperty of QuickAccessMenuItem to a BoolProperty (PasteToQuickAccess) in a ViewModel like "UserSettingsVM":
_<UserControl x:Class="FluentTest.MyQAT"
   ...>
  <StackPanel>
     <Fluent:QuickAccessMenuItem Target="{Binding Source={x:Reference pasteButton}}"
                                                        Visibility="{Binding UserSettingsVM.PasteToQuickAccess, Converter={StaticResource BoolToVisibleOrCollapsedConverter}}/>
     ...
   </StackPanel>
</UserControl>_
And now try to use this UserControl "MyQAT.xaml" in your UserControl "TestContent.xaml".
I try with:
_<Grid.Resources>
   ...
   <ControlTemplate x:Key="MyQAT">
      <local:MyQAT/>
   </ControlTemplate>
 </Grid.Resources>
 <Fluent:Ribbon ...>
   ...
   <Fluent:Ribbon.QuickAccessItems>
       <Fluent:QuickAccessMenuItem Template="{StaticResource MyQAT}"/>
   </Fluent:Ribbon.QuickAccessItems>
   ...
  </Fluent.Ribbon>_
1)
In **<Fluent:QuickAccessMenuItem Template="{StaticResource MyQAT}"/>** I get the ErrorMessage:
![image](https://cloud.githubusercontent.com/assets/22076843/21385667/b2f59944-c76f-11e6-86f1-bcdb8ddc09c7.png)
Yes I know, that's the missing Reference for the Target-Sources in MyQAT, but that is the first issue, because my Buttons are in several other UserControls binding in Fluent.Ribbon as ControlTemplates for the RibbonTabs. 
**How the Reference set to Buttons in other Control???**
2)
I've deleted all MenuItems accept the "<Fluent:Button Header="Pink". The Device to the Icon-Source is missing (see Picture below) and this Button isn't added to the QAT and can't add to QAT!!!
![image](https://cloud.githubusercontent.com/assets/22076843/21386979/d832a4da-c775-11e6-8418-c0202604736b.png)
3)
As you can see, the old QuickAccessMenuItems are still shown in the QAT although there are no more QuickAccessItems in the ControlTemplate "MyQAT". 
**Where are These Entries saved???**

**Comment by batzen** [comment]
By repro i mean your "FluentTest" project. Just create a zip file containing everything i need to reproduce your issue.
In german: Schick mir einfach dein Test-Projekt (repro meint Test-Projekt oder Reproduzier-Projekt). Ist immer die einfachere Lösung. Du musst nicht lang erklären, welchen code ich brauche um das gleiche zu produzieren und ich muss mir nichts aus den Nachrichten zusammensuchen.

> in an earlier issue I read, that your interest in QAT is going to Zero :-) But our users want to manage several Functions in a QAT, so we have to implement this.

It is going to zero but it's not zero. It's just that I don't test it very much. If it's high priority for you, feel free to fix the issue and submit a PR. ;-)

1. 

> How the Reference set to Buttons in other Control???

You can't reference controls contained in an outer scope by using the ElementName in a binding. You'd either have to use code behind in the control or use separate properties on your control to inject the control instances from the outside. There might be other ways to do it, but those should be the easiest and most obvious.

2. I don't get what you are trying to tell me here.

3. 
> Where are These Entries saved???

Isolated storage for your application. In my case it's `C:\Users\Bastian\AppData\Local\IsolatedStorage\fwzic1g4.ljf\xcvyjpr4.dia\Url.0lz2wgn5a5ft3axefx0sxm5fnarux15b\StrongName.gjg0mtp25wkbtf2255s4ljvyyques1l5\Files\` for the showcase application.

**Comment by juergschweigi** [comment]
OK,
here my TestProject
[TestFluent.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/668271/TestFluent.zip)

**Comment by batzen** [comment]
Ok, now i see your issue.

You can't simply set Template of QuickAccessMenuItem to a control containing multiple QuickAccessMenuItem to get some kind of dynamic menu, that's just not the way WPF works in general.

If you want to get a dynamic menu you should use some kind of factory to inject QuickAccessMenuItem instances into Ribbon:QuickAccessMenuItems.

**Comment by juergschweigi** [comment]
OK,
thank's for spending your time. The effort is too big, so i will Limit the number of functions with QuickAccess.
