### ISSUE TITLE
Window "Not Responding" cut Title

### ISSUE THREAD

**Issue by loewnzaan** [fluentribbon/Fluent.Ribbon#80]
Hello.

When my Application loaded a Long time and the RibbonWindow say in titlebar "Not Responding", but his work takes a few seconds back on, the RibbonWindow is moved some Pixels at top and left.  So the titlebar is cut. When the window is minimized and maximized after the hanging again everything is right again.
Is this the "WindowChrome"-Bug?

Use this code on ButtonClick as sample to simulate the hanging:

Thread.Sleep(10000)

and click at the loading time in the window. This code make the "Not Responding" only when you start the Application from the Explorer. In Debug-Mode the "Not Responding" doesn't come ... just as a tip!

Greeting, Flo

**Comment by batzen** [comment]
Can't reproduce.
Which theme are you using?
A screenshot would help a lot. ;-)

**Comment by loewnzaan** [comment]
<img src="http://hshighscore.cwsurf.de/Unbenannt.png"/>

Hi!

Sorry for the late reply. The first picture is normally, the second is when "not responding" and the last picture ist after "not responding".

When i minimize and then maximize the Window after not responding, the window is ok again.

Thx

**Comment by batzen** [comment]
Ah, you are using Windows 7 that's the reason why I couldn't reproduce it here.
Yes, that looks like one of the WindowChrome bugs. If it just renders black without buttons it's one of the WindowChrome bugs...

Will have a look at this sometime this week to figure out which route we could take here to fix this.

**Comment by batzen** [comment]
Maybe this week...

**Comment by batzen** [comment]
I don't know how to fix the current issues, including this one, related to the microsoft WindowChrome class. Any suggestions from anyone?

**Comment by loewnzaan** [comment]
I have a idea 💡! I post next week a little code when I come home.

**Comment by batzen** [comment]
Nice to hear that.

**Comment by batzen** [comment]
Can someone check if this is really fixed now? Got no Windows 7 machine here.

**Comment by chdft** [comment]
I've tested on Windows 7 SP1 (both FluentTest for .Net 4.0 and 4.5) and the issue was fixed in all themes. The window looks normal (not shifted to the top left, aero glass works fine) even after the window was rated "not responding"; it still gets shifted to the top left *while* the application is not responding though, but I don't think that that is fixable.

**Comment by batzen** [comment]
It may be fixable, but not now as that will take much more time.
